# Generated by Django 4.2.5 on 2023-09-19 09:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Yaratuvchi',
                'verbose_name_plural': 'Yaratuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Izoh')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Rasm')),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.creator')),
            ],
            options={
                'verbose_name': 'Telefonlar',
                'verbose_name_plural': 'Telefonlar',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('value', models.CharField(choices=[('+', 'yaxshi'), ('-', 'yomon')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('body', models.CharField(max_length=200)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_review', to='news.project')),
            ],
            options={
                'verbose_name': 'Ball',
                'verbose_name_plural': 'Ball',
            },
        ),
    ]
