# Generated by Django 4.2.5 on 2023-09-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_review_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ManyToManyField(blank=True, to='news.tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
