# Generated by Django 4.2.5 on 2023-09-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_tag_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(choices=[('1', 'yaxshi'), ('2', 'yomon')], default='1', max_length=2),
        ),
    ]
