# Generated by Django 4.2.5 on 2023-09-16 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_review_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='creator',
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.creator'),
        ),
    ]
