# Generated by Django 4.2.5 on 2023-09-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_project_creator_project_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'verbose_name': 'Yaratuvchi', 'verbose_name_plural': 'Yaratuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Telefonlar', 'verbose_name_plural': 'Telefonlar'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Ball', 'verbose_name_plural': 'Ball'},
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nomi'),
        ),
    ]
