# Generated by Django 4.2.5 on 2023-09-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_creator_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('+', 'yaxshi'), ('-', 'yomon')], default=5, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_review', to='news.project'),
        ),
    ]
