"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@x69j^ruw-q7wdb_ha%qj)h73!*dokt688k1!r7e_k0y*r*i-f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'news',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Jazzmin settings default
JAZZMIN_SETTINGS = {
    # Ilovada sarlavha sarlavhasi (ko'rsatilmagan yoki None bo'lsa, current_admin_site.site_title orqali belgilanadi)
    "site_title": "Library Admin",

    # Kirish sahifasining sarlavhasi (maksimum 19 belgidan ko'p emas) (ko'rsatilmagan yoki None bo'lsa,
    # current_admin_site.site_header qiymati ishlatiladi)
    "site_header": "Kirish sahifasi",

    # Brendni sarlavhasi (maksimum 19 belgidan ko'p emas) (ko'rsatilmagan yoki None bo'lsa, current_admin_site.site_header qiymati ishlatiladi)
    "site_brand": "Library",

    # Saytingiz uchun logo, bu logo brandingdan foydalanish uchun ishlatiladi (static fayllar orqali mavjud bo'lishi kerak)
    "site_logo": "/static.img.logo.png",

    # Saytingiz uchun login oynasiga ishlatiladigan logo (ko'rsatilmagan yoki None bo'lsa, site_logo qiymati ishlatiladi)
    "login_logo": None,

    # Tungi mavjudligida login formasiga ishlatiladigan logo (login_logo qiymati ishlatiladi)
    "login_logo_dark": None,

    # Logo ustiga qo'yiladigan CSS sinfi
    "site_logo_classes": "img-circle",

    # Saytingiz uchun favicon (site_logo bo'lmagan holda site_logo ga mos ravishda ko'rinishi kerak, ideal tarzda 32x32 piksel o'lchamdagi rasm)
    "site_icon": None,

    # Kirish sahifasidagi xush kelibsiz matni
    "welcome_sign": "Login va Parol kiriting",

    # Ushbu proyektingizning copytighti (footerda chiqadi)
    "copyright": "Namangan state university",

    # Qidiruv qutisida ko'rsatiladigan model adminlari ro'yxati (agar ko'rsatilmagan bo'lsa, qidiruv quti olib tashlanadi)
    # Agar faqat bitta qidiruv qutisini ishlatmoqchi bo'lsangiz, o'zi yozing
    "search_model": ["auth.User", "auth.Group"],

    # Foydalanuvchi modelida avatar uchun maydon nomi (ImageField/URLField/Charfield yoki foydalanuvchi obyekti qabul qiluvchi funksiya)
    "user_avatar": None,

    # Yuqori menuga qo'shiladigan havolalar ro'yxati
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.User"},
        {"app": "books"},
    ],

    # Foydalanuvchi menusi ustiga qo'shiladigan havolalar ro'yxati
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.user"}
    ],

    # Yon menuni ko'rsatish (Menuni ko'rsatish uchun ishlatiladimi)
    "show_sidebar": True,

    # Menuni avtomatik ravishda o'zgartirish (Menuni avtomatik ravishda o'zgartirish uchun ishlatiladimi)
    "navigation_expanded": True,

    # Menuni generatsiyalashda olib tashlash (ko'rsatilmagan bo'lsa, auth va hujjat kiritilgan bo'lsa, ulardan tashqariladi)
    "hide_apps": [],

    # Menuni generatsiyalashda olib tashlash (ko'rsatilmagan bo'lsa, auth va hujjat kiritilgan bo'lsa, ulardan tashqariladi)
    "hide_models": [],

    # Menuni tartiblash uchun apps (va yoki modellarni) bazasini belgilash (hamma apps/ modellarni o'z ichiga olishi kerak emas)
    "order_with_respect_to": ["auth", "books", "books.author", "books.book"],

    # App guruhi qo'shish uchun eng pastga joylashtirish uchun maxsus havolalar
    "custom_links": {
        "books": [{
            "name": "Make Messages",
            "url": "make_messages",
            "icon": "fas fa-comments",
            "permissions": ["books.view_book"]
        }]
    },

    # Side Menu apps/ modellar uchun maxsus ikonlar
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },

    # Agar ma'lum bir ikon ko'rsatilmagan bo'lsa ishlatiladigan ikonlar
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    # Bog'liq Modalni ishlatish (Popaplar o'rniga modallar ishlatiladi)
    "related_modal_active": False,

    # UI Tweakslar
    "custom_css": None,  # Maxsus CSS/JS skriptlarining manzillari (static fayllarda bo'lishi kerak)
    "custom_js": None,
    "use_google_fonts_cdn": True,  # fonts.googleapis.com dan font ulash (fontlarni manba CSS bilan yetkazib berish uchun custom_css ni ishlatish mumkin)

    # UI customizer ni sidebar ichida ko'rsatish kerak bo'lsa
    "show_ui_builder": False,

    # O'zgarish sahifasini tuzatish
    "changeform_format": "horizontal_tabs",  # Bitta shakl ko'rsatish (single), yatqich bo'limlar (horizontal_tabs, default), oddiy bo'limlar (vertical_tabs), murakkab bo'limlar (collapsible), karusel (carousel)
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},  # modeladminlar bo'yicha o'zgarish shaklini ko'rib chiqarish
    "language_chooser": False,  # Ilovaga til tanlash quti qo'shish
}

# /Jazzmin settings default
